const $=id=>document.getElementById(id);const invoke=window.__TAURI__?.core?.invoke;const KEY='gearpilot-v0.5';
const defaults={profiles:[{id:'everyday',name:'Everyday',dpi:1400,poll:250,color:'#5ea0ff',effect:'Solid'},{id:'fps',name:'FPS Gaming',dpi:1400,poll:1000,color:'#5ea0ff',effect:'Reactive'},{id:'low',name:'Low Power',dpi:800,poll:125,color:'#5ea0ff',effect:'Off'}],activeProfile:'everyday',selected:null,filter:'all',search:'',settings:{autoScan:5,safeMode:true,accent:'blue'}};
let state=load(),devices=[],drivers=[],timer,keyEvents=0,mouseEvents=0;
function load(){try{const current=localStorage.getItem(KEY);if(current)return {...defaults,...JSON.parse(current)};for(const k of ['periph-v0.4','periph-v0.3']){const old=localStorage.getItem(k);if(old){const x=JSON.parse(old);return {...defaults,profiles:x.profiles||defaults.profiles,settings:{...defaults.settings,...x.settings}}}}}catch{}return structuredClone(defaults)}function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function hex(n){return '0x'+Number(n||0).toString(16).toUpperCase().padStart(4,'0')}
function group(raw){const m=new Map;for(const d of raw){const g=m.get(d.groupId)||{id:d.groupId,name:d.product||'Unknown HID device',manufacturer:d.manufacturer||d.vendorTag||'Unknown',kind:d.kind,vid:d.vendorId,pid:d.productId,bus:d.busType,driverId:d.driverId,driverStatus:d.driverStatus,interfaces:[]};g.interfaces.push(d);if(d.kind==='keyboard'||d.kind==='mouse')g.kind=d.kind;m.set(d.groupId,g)}return [...m.values()]}
function demoDevice(){return {id:'demo-keyboard',name:'GearPilot Demo Keyboard',manufacturer:'Demo',kind:'keyboard',vid:0x1234,pid:0x0500,bus:'usb',driverId:'generic-hid',driverStatus:'inspect-only',interfaces:[{interfaceNumber:0,usagePage:1,usage:6,path:'redacted'}],demo:true}}
async function scan(){setScan('Scanning…');try{const r=invoke?await invoke('scan_devices'):{interfaces:[]};devices=group(r.interfaces||[]);if(!devices.length&&location.search.includes('demo=1'))devices=[demoDevice()];if(state.selected&&!devices.some(d=>d.id===state.selected))state.selected=null;if(!state.selected&&devices[0])state.selected=devices[0].id;save();renderAll();setScan(`${devices.length} device${devices.length===1?'':'s'}`)}catch(e){setScan('Scan failed');toast(String(e))}}
function setScan(t){$('scanState').innerHTML=`<i></i> ${esc(t)}`}
function selected(){return devices.find(d=>d.id===state.selected)}function profile(){return state.profiles.find(p=>p.id===state.activeProfile)||state.profiles[0]}
function renderDevices(){const q=state.search.toLowerCase();const list=devices.filter(d=>(state.filter==='all'||d.kind===state.filter)&&`${d.name} ${d.manufacturer} ${hex(d.vid)} ${hex(d.pid)}`.toLowerCase().includes(q));$('deviceList').innerHTML=list.length?list.map(d=>`<div class="device-item ${d.id===state.selected?'active':''}" data-device="${esc(d.id)}"><div class="device-symbol">${d.kind==='mouse'?'●':'⌨'}</div><div class="device-copy"><b>${esc(d.name)}</b><span>${esc(d.manufacturer)} · ${hex(d.vid)}:${hex(d.pid)}</span></div></div>`).join(''):'<div class="device-item"><div class="device-copy"><b>No devices</b><span>Connect one and scan</span></div></div>';document.querySelectorAll('[data-device]').forEach(x=>x.onclick=()=>{state.selected=x.dataset.device;save();renderAll()})}
function art(kind){if(kind==='mouse')return '<div class="mouse-art"></div>';return `<div class="keyboard-art">${'<i></i>'.repeat(48)}</div>`}
function renderWorkspace(){const d=selected();$('empty').classList.toggle('hidden',!!d);$('workspace').classList.toggle('hidden',!d);if(!d)return;$('deviceVendor').textContent=(d.manufacturer||'Peripheral').toUpperCase();$('deviceName').textContent=d.name;$('deviceMeta').textContent=`${hex(d.vid)}:${hex(d.pid)} · ${d.bus||'HID'} · ${d.interfaces.length} interface${d.interfaces.length===1?'':'s'}`;$('badges').innerHTML=`<span class="badge ${d.driverStatus==='foundation'?'ok':''}">${esc(d.driverStatus||'inspect-only')}</span><span class="badge">${esc(d.kind)}</span><span class="badge locked">Writes locked</span>`;$('deviceArt').innerHTML=art(d.kind);const p=profile();$('activeProfileName').textContent=p.name;$('activeProfileSummary').textContent=`${p.dpi} DPI target · ${p.poll} Hz target`;$('supportTitle').textContent=d.driverStatus==='foundation'?'Driver foundation':'Inspect only';$('supportList').innerHTML=`<div><b>Discovery</b><span>Ready</span></div><div><b>Diagnostics</b><span>Ready</span></div><div><b>Hardware writes</b><span>Locked</span></div>`;$('dpi').value=p.dpi;$('poll').value=p.poll;$('dpiValue').textContent=`${p.dpi} DPI`;$('pollValue').textContent=`${p.poll} Hz`;$('effect').value=p.effect;$('color').value=p.color;light();$('diag').textContent=JSON.stringify({name:d.name,manufacturer:d.manufacturer,kind:d.kind,vid:hex(d.vid),pid:hex(d.pid),transport:d.bus,driver:d.driverId,status:d.driverStatus,interfaces:d.interfaces.map(i=>({interface:i.interfaceNumber,usagePage:hex(i.usagePage),usage:hex(i.usage)})),privateFields:'redacted'},null,2)}
function renderProfiles(){$('profileList').innerHTML=state.profiles.map(p=>`<div class="panel profile"><div><b>${esc(p.name)}</b><span>${p.dpi} DPI · ${p.poll} Hz · ${esc(p.effect)}</span></div><button class="btn ${p.id===state.activeProfile?'primary':'secondary'}" data-profile="${esc(p.id)}">${p.id===state.activeProfile?'Active':'Use'}</button></div>`).join('');document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{state.activeProfile=b.dataset.profile;save();renderAll();toast('Profile activated')})}
function renderDrivers(){$('driverList').innerHTML=(drivers.length?drivers:[{name:'Generic HID Inspector',vendor:'Any',supportLevel:'inspect-only',notes:'Safe fallback for unknown HID devices.'},{name:'Apple Magic Keyboard',vendor:'Apple',supportLevel:'foundation',notes:'Read/write work is intentionally gated by exact tested models.'},{name:'Glorious Model O',vendor:'Glorious',supportLevel:'foundation',notes:'Revision-specific support foundation.'}]).map(d=>`<article class="panel driver"><small>${esc((d.vendor||'ANY').toUpperCase())}</small><h3>${esc(d.name)}</h3><p>${esc(d.notes||'')}</p><span class="badge ${d.supportLevel==='foundation'?'ok':''}">${esc(d.supportLevel||'inspect-only')}</span></article>`).join('')}
function renderSettings(){$('autoScan').value=state.settings.autoScan;$('safeMode').checked=state.settings.safeMode;$('accent').value=state.settings.accent;applyAccent()}
function renderDashboard(){const p=profile(),d=selected();$('dashDeviceCount').textContent=devices.length;$('dashDeviceText').textContent=devices.length?`${devices.length} device${devices.length===1?'':'s'} ready`:'No devices detected';$('dashProfile').textContent=p?.name||'Everyday';$('dashProfileMeta').textContent=p?`${p.dpi} DPI · ${p.poll} Hz`:'Portable profile';$('dashSelected').textContent=d?.name||'Nothing selected';$('dashStatus').textContent=d?(d.driverStatus||'inspect-only'):'Waiting for scan';$('dashStatus').className=`badge ${d?.driverStatus==='foundation'?'ok':''}`;$('dashSelectedMeta').textContent=d?`${d.manufacturer||'Peripheral'} · ${hex(d.vid)}:${hex(d.pid)} · ${d.bus||'HID'}`:'Connect a keyboard or mouse and GearPilot will identify it safely.'}
function renderAll(){renderDashboard();renderDevices();renderWorkspace();renderProfiles();renderDrivers();renderSettings()}
function applyAccent(){const c={blue:'#5ea0ff',green:'#55d18b',gold:'#f0bf55',violet:'#9a7cff'}[state.settings.accent]||'#5ea0ff';document.documentElement.style.setProperty('--accent',c);document.documentElement.style.setProperty('--accentSoft',c+'22')}
function show(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const names={dashboard:['GEARPILOT','Dashboard'],devices:['DEVICE','Device workspace'],profiles:['PROFILES','Portable profiles'],tester:['INPUT TESTER','Input tester'],drivers:['DRIVERS','Driver center'],settings:['SETTINGS','Preferences']};$('eyebrow').textContent=names[view][0];$('title').textContent=names[view][1]}
function light(){const p=profile(),c=$('color')?.value||p.color,b=Number($('brightness')?.value||80)/100;$('lightPreview')?.style.setProperty('--accent',c);if($('lightPreview'))$('lightPreview').style.opacity=.35+.65*b}
function logEvent(t){const now=new Date().toLocaleTimeString();$('eventLog').innerHTML=`<div>${now} · ${esc(t)}</div>`+$('eventLog').innerHTML;$('eventLog').firstElementChild?.scrollIntoView({block:'nearest'})}
function exportJson(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$('dashScan').onclick=scan;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.kind;renderDevices()});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabpane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`tab-${b.dataset.tab}`).classList.add('active')});
$('search').oninput=e=>{state.search=e.target.value;renderDevices()};for(const id of ['scan','scanSmall','emptyScan'])$(id).onclick=scan;$('demo').onclick=()=>{devices=[demoDevice()];state.selected='demo-keyboard';renderAll();setScan('Demo mode')};$('backup').onclick=()=>exportJson('gearpilot-backup.json',{schema:5,state});$('copyDiag').onclick=async()=>{await navigator.clipboard.writeText($('diag').textContent);toast('Diagnostics copied')};
$('dpi').oninput=e=>{$('dpiValue').textContent=`${e.target.value} DPI`};$('dpi').onchange=e=>{profile().dpi=Number(e.target.value);save();renderProfiles()};$('poll').onchange=e=>{profile().poll=Number(e.target.value);$('pollValue').textContent=`${e.target.value} Hz`;save();renderProfiles()};$('color').oninput=e=>{profile().color=e.target.value;save();light()};$('brightness').oninput=light;$('effect').onchange=e=>{profile().effect=e.target.value;save();renderProfiles()};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{state.activeProfile=b.dataset.preset==='everyday'?'everyday':b.dataset.preset;save();renderAll();toast('Profile activated')});$('autoScan').onchange=e=>{state.settings.autoScan=Number(e.target.value);save();startAuto()};$('safeMode').onchange=e=>{state.settings.safeMode=e.target.checked;save()};$('accent').onchange=e=>{state.settings.accent=e.target.value;save();applyAccent()};
$('keyTester').addEventListener('keydown',e=>{e.preventDefault();keyEvents++;$('lastKey').textContent=e.key===' '?'Space':e.key;$('keyCount').textContent=`${keyEvents} events`;logEvent(`Key ${e.key}`)});$('mouseTester').addEventListener('contextmenu',e=>e.preventDefault());$('mouseTester').addEventListener('mousedown',e=>{mouseEvents++;const id=e.button===0?'leftBtn':e.button===1?'middleBtn':'rightBtn';$(id).classList.add('hit');$('mouseCount').textContent=`${mouseEvents} events`;logEvent(`Mouse button ${e.button}`)});$('mouseTester').addEventListener('mouseup',()=>document.querySelectorAll('.mouse span').forEach(x=>x.classList.remove('hit')));$('mouseTester').addEventListener('wheel',e=>{mouseEvents++;$('mouseCount').textContent=`${mouseEvents} events`;logEvent(`Wheel ${Math.sign(e.deltaY)>0?'down':'up'}`)},{passive:true});
function startAuto(){clearInterval(timer);if(state.settings.autoScan)timer=setInterval(scan,state.settings.autoScan*1000)}
(async()=>{try{if(invoke){drivers=await invoke('driver_catalog');const info=await invoke('app_info');$('runtime').textContent=`${info.name} ${info.version} · ${info.platform}/${info.arch}`}}catch{}renderAll();startAuto();await scan()})();
